// $ANTLR 2.7.6 (20190807): "gramatica.g" -> "MeuParser.java"$

public interface MeuParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int LITERAL_programa = 4;
	int LITERAL_fimprog = 5;
	int T_pontof = 6;
	int LITERAL_declare = 7;
	int LITERAL_como = 8;
	int LITERAL_String = 9;
	int T_Id = 10;
	int T_virg = 11;
	int LITERAL_Inteiro = 12;
	int LITERAL_Decimal = 13;
	int LITERAL_leia = 14;
	int T_ap = 15;
	int T_fp = 16;
	int LITERAL_escreva = 17;
	int T_texto = 18;
	int LITERAL_recebe = 19;
	int LITERAL_se = 20;
	int LITERAL_entao = 21;
	int T_cha = 22;
	int T_chf = 23;
	int LITERAL_senao = 24;
	int LITERAL_enquanto = 25;
	int LITERAL_para = 26;
	int T_pontVirg = 27;
	int LITERAL_escolha = 28;
	int LITERAL_caso = 29;
	int T_num = 30;
	int LITERAL_faca = 31;
	int LITERAL_Mais = 32;
	int LITERAL_Menos = 33;
	int LITERAL_MultiplicadoPor = 34;
	int LITERAL_DivididoPor = 35;
	int LITERAL_ElevadoA = 36;
	int LITERAL_eMenorQue = 37;
	int LITERAL_eMaiorQue = 38;
	int LITERAL_eMenorEIgualQue = 39;
	int LITERAL_eMaiorEIgualQue = 40;
	int LITERAL_eDiferenteDe = 41;
	int LITERAL_eIgualQue = 42;
	int T_blank = 43;
}
