// $ANTLR 2.7.6 (20190807): "gramatica.g" -> "MeuParser.java"$

public interface MeuParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int LITERAL_programa = 4;
	int LITERAL_fimprog = 5;
	int T_pontof = 6;
	int LITERAL_declare = 7;
	int T_Id = 8;
	int T_virg = 9;
	int LITERAL_leia = 10;
	int T_ap = 11;
	int T_fp = 12;
	int LITERAL_escreva = 13;
	int T_texto = 14;
	int LITERAL_recebe = 15;
	int LITERAL_se = 16;
	int LITERAL_entao = 17;
	int T_cha = 18;
	int T_chf = 19;
	int LITERAL_senao = 20;
	int LITERAL_enquanto = 21;
	int LITERAL_para = 22;
	int T_pontVirg = 23;
	int LITERAL_escolha = 24;
	int LITERAL_caso = 25;
	int T_num = 26;
	int LITERAL_faca = 27;
	int LITERAL_Mais = 28;
	int LITERAL_Menos = 29;
	int LITERAL_MultiplicaPor = 30;
	int LITERAL_DividePor = 31;
	int LITERAL_ElevadoA = 32;
	int LITERAL_eMenorQue = 33;
	int LITERAL_eMaiorQue = 34;
	int LITERAL_eMenorEIgualQue = 35;
	int LITERAL_eMaiorEIgualQue = 36;
	int LITERAL_eDiferenteDe = 37;
	int LITERAL_eIgualQue = 38;
	int T_blank = 39;
}
